"$schema" = "https://starship.rs/config-schema.json"
add_newline = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[cmd_duration]
min_time = 2000   # show duration only for commands slower than 2 seconds
